project:
  type: website
  output-dir: docs
 
website:
  title: "text-analysis-with-R"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

