---
title: "Program"
---

## Advanced techniques in text analysis with R

-   9:00 am - 9:30 am: Overview of text classification techniques beyond topic modeling: unsupervised and supervised methods.

-   9:30 am - 10:30 am: Unsupervised text classification: Text scaling, correspondence analysis, clustering, and applications in communication science.

-   10:30 am - 11:00 am: Break.

-   11:00 am - 12:00 pm: Unsupervised text classification: hands-on exercises using real-world data sets.

-   12:00 pm - 1:00 pm: Lunch.

-   1:00 pm - 2:00 pm: Supervised classification: using R to classify text data into different categories, with an overview of algorithms.

-   2:00 pm - 3:00 pm: Using R to perform supervised text classification: hands-on exercises using real-world data sets.

-   3:00 pm - 3:30 pm: Coffee Break.

-   3:30 pm - 4:30 pm: Overview of other advanced techniques in text analysis (word embedding, network analysis, named entity recognition).

-   4:30 pm - 5:00 pm: Conclusion and wrap-up of the seminar.
